/*
 * Writes the Sponza flythrough as a poses file for tools/r3d's
 * triangle_sizes: the lens and render size scene_sponza.c uses, and a pose
 * every 5 s of the loop, the poses suite_sponza_perf.c times.
 */
#include <stdio.h>

#include "apps/render_lab/sponza_flythrough.h"

#define SAMPLE_EVERY_MS 5000

int
main(void) {
    int failed = printf("# Generated by gen_sponza_poses.sh - do not edit.\n") < 0;
    failed |= printf("size %d %d\nlens %.6g %.6g\n", SPONZA_RENDER_WIDTH, SPONZA_RENDER_HEIGHT,
                     (double)SPONZA_HALF_FOV_SHORT_TAN, (double)SPONZA_NEAR_Z)
              < 0;
    const uint32_t period = r3d_path_period_ms(&sponza_flythrough);
    for (uint32_t t_ms = 0; t_ms < period; t_ms += SAMPLE_EVERY_MS) {
        r3d_vec3f_t eye;
        r3d_vec3f_t forward;
        r3d_path_sample(&sponza_flythrough, t_ms, &eye, &forward);
        failed |= printf("pose %.9g %.9g %.9g %.9g %.9g %.9g\n", (double)eye.x, (double)eye.y, (double)eye.z,
                         (double)forward.x, (double)forward.y, (double)forward.z)
                  < 0;
    }
    return failed;
}
