import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import code_layout  # noqa: E402


class PinnedFunctionTests(unittest.TestCase):
    def test_a_pin_is_found_whether_static_or_not(self):
        source = ("static RENDER_ENTRY_OFFSET(6) void\nwalk_rows(int y0) {\n}\n"
                  "RENDER_ENTRY_OFFSET(12) raster_stats_t\nraster_draw(const raster_t* raster) {\n}\n"
                  "void\nunpinned(void) {\n}\n")
        self.assertEqual(code_layout.pinned_functions([source]), ["walk_rows", "raster_draw"])

    def test_the_macro_definition_itself_is_not_a_pin(self):
        header = "#define RENDER_ENTRY_OFFSET(slots) __attribute__((patchable_function_entry(slots, slots)))\n"
        self.assertEqual(code_layout.pinned_functions([header]), [])


class LineSpanTests(unittest.TestCase):
    def test_a_loop_inside_one_line_spans_one(self):
        self.assertEqual(code_layout.line_span(0x40, 0x40 + 32, 32), 1)

    def test_a_loop_crossing_a_line_boundary_spans_two(self):
        self.assertEqual(code_layout.line_span(0x5c, 0x5c + 8, 32), 2)


class PoolTests(unittest.TestCase):
    # As objdump decodes r3d_span_triangle_impl: a short jump over a literal
    # pool whose bytes read as a backward branch.
    FOUND = [
        (0x1100, 3, "bnez", "a10, 1120 <f+0x20>"),
        (0x1103, 3, "j", "110c <f+0xc>"),
        (0x1106, 3, "blti", "a5, 7, 10f0 <f-0x10>"),
        (0x1109, 3, "src", "a0, a0, a0"),
        (0x110C, 2, "mov.n", "a10, a6"),
        (0x110E, 3, "j", "1100 <f>"),
        (0x1111, 3, "j", "1200 <f+0x100>"),
        (0x1114, 3, "addi", "a2, a2, 1"),
    ]

    def test_what_a_short_forward_jump_skips_is_dropped(self):
        kept = [address for address, _, _, _ in code_layout.skip_pools(self.FOUND)]
        self.assertEqual(kept, [0x1100, 0x1103, 0x110C, 0x110E, 0x1111, 0x1114])

    def test_code_a_branch_enters_is_kept_though_jumped_over(self):
        found = [
            (0x1300, 3, "beqz", "a2, 1306 <g+0x6>"),
            (0x1303, 3, "j", "130c <g+0xc>"),
            (0x1306, 3, "addi", "a3, a3, 1"),
            (0x1309, 3, "bnez", "a3, 1306 <g+0x6>"),
            (0x130C, 2, "retw.n", ""),
        ]
        self.assertEqual(code_layout.skip_pools(found), found)


class BackwardBranchTests(unittest.TestCase):
    def test_a_branch_back_inside_the_function_is_a_row(self):
        self.assertTrue(code_layout.backward_within(0x1100, 0x1180, 0x1000))

    def test_a_branch_back_out_of_the_function_is_not(self):
        # As objdump read r3d_span_triangle_impl out of step past a pool:
        # a "j" to pthread_create, 122440 bytes back.
        self.assertFalse(code_layout.backward_within(0x42008778, 0x420265BD, 0x42025DF4))

    def test_a_forward_branch_is_not(self):
        self.assertFalse(code_layout.backward_within(0x1200, 0x1180, 0x1000))


class LayoutCheckTests(unittest.TestCase):
    BASELINE = """\
# Generated by: python launcher/tools/render/code_layout.py --write launcher/build.diag
function\tkind\toffset\tbytes\tlines
raster_draw\tfunction\t0\t40\t2
raster_draw\tloop\t4\t20\t1
shade_span\tfunction\t8\t48\t2
"""

    def differences(self, current):
        expected = code_layout.parse_layout(self.BASELINE)
        actual = code_layout.parse_layout(current)
        return code_layout.layout_differences(expected, actual)

    def test_an_unchanged_layout_passes(self):
        self.assertEqual(self.differences(self.BASELINE), [])

    def test_an_offset_change_names_the_row(self):
        current = self.BASELINE.replace("raster_draw\tloop\t4", "raster_draw\tloop\t6")
        self.assertEqual(self.differences(current), ["raster_draw loop[1]: offset 4 -> 6"])

    def test_a_loop_line_count_change_names_the_row(self):
        current = self.BASELINE.replace("raster_draw\tloop\t4\t20\t1", "raster_draw\tloop\t4\t20\t2")
        self.assertEqual(self.differences(current), ["raster_draw loop[1]: lines 1 -> 2"])

    def test_an_added_or_removed_pin_names_the_function(self):
        added = self.BASELINE + "new_draw\tfunction\t16\t24\t2\n"
        removed = self.BASELINE.replace("shade_span\tfunction\t8\t48\t2\n", "")
        self.assertEqual(self.differences(added), ["new_draw function: pin added"])
        self.assertEqual(self.differences(removed), ["shade_span function: pin removed"])


if __name__ == "__main__":
    unittest.main()
