import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import code_layout  # noqa: E402


class PinnedFunctionTests(unittest.TestCase):
    def test_a_pin_is_found_whether_static_or_not(self):
        source = ("static RENDER_ENTRY_OFFSET(6) void\nwalk_rows(int y0) {\n}\n"
                  "RENDER_ENTRY_OFFSET(12) raster_stats_t\nraster_draw(const raster_t* raster) {\n}\n"
                  "void\nunpinned(void) {\n}\n")
        self.assertEqual(code_layout.pinned_functions([source]), ["walk_rows", "raster_draw"])

    def test_the_macro_definition_itself_is_not_a_pin(self):
        header = "#define RENDER_ENTRY_OFFSET(slots) __attribute__((patchable_function_entry(slots, slots)))\n"
        self.assertEqual(code_layout.pinned_functions([header]), [])


class LineSpanTests(unittest.TestCase):
    def test_a_loop_inside_one_line_spans_one(self):
        self.assertEqual(code_layout.line_span(0x40, 0x40 + 32, 32), 1)

    def test_a_loop_crossing_a_line_boundary_spans_two(self):
        self.assertEqual(code_layout.line_span(0x5c, 0x5c + 8, 32), 2)


class LayoutCheckTests(unittest.TestCase):
    BASELINE = """\
# Generated by: python launcher/tools/render/code_layout.py --write launcher/build.diag
function\tkind\toffset\tbytes\tlines
raster_draw\tfunction\t0\t40\t2
raster_draw\tloop\t4\t20\t1
shade_span\tfunction\t8\t48\t2
"""

    def differences(self, current):
        expected = code_layout.parse_layout(self.BASELINE)
        actual = code_layout.parse_layout(current)
        return code_layout.layout_differences(expected, actual)

    def test_an_unchanged_layout_passes(self):
        self.assertEqual(self.differences(self.BASELINE), [])

    def test_an_offset_change_names_the_row(self):
        current = self.BASELINE.replace("raster_draw\tloop\t4", "raster_draw\tloop\t6")
        self.assertEqual(self.differences(current), ["raster_draw loop[1]: offset 4 -> 6"])

    def test_a_loop_line_count_change_names_the_row(self):
        current = self.BASELINE.replace("raster_draw\tloop\t4\t20\t1", "raster_draw\tloop\t4\t20\t2")
        self.assertEqual(self.differences(current), ["raster_draw loop[1]: lines 1 -> 2"])

    def test_an_added_or_removed_pin_names_the_function(self):
        added = self.BASELINE + "new_draw\tfunction\t16\t24\t2\n"
        removed = self.BASELINE.replace("shade_span\tfunction\t8\t48\t2\n", "")
        self.assertEqual(self.differences(added), ["new_draw function: pin added"])
        self.assertEqual(self.differences(removed), ["shade_span function: pin removed"])


if __name__ == "__main__":
    unittest.main()
